### ISSUE TITLE
Reformatting text

### ISSUE THREAD

**Issue by RuthAngus** [jradavenport/k2rot_adap#3]
Hi Jim, 

I just wanted to mention that I use some conventions when I write tex and I have applied these to the  parts that I've edited because it's easier for me to then edit in vim! Specifically, I allow no more than 80 characters per line and I start a new line for every sentence. I hope this doesn't bother you!

**Comment by jradavenport** [comment]
80 char / line doesn't bother me -I hope my edits that change it sometimes don't bother you :)

**Comment by RuthAngus** [comment]
Not at all! This wasn't meant to sound like a passive-aggressive hint for you to follow the same conventions, but I realise it may have come across that way, haha!

**Comment by jradavenport** [comment]
👍
